DDCE-1001: Added allowed Country codes functionality to Charity's off…
hmrc/charities-registration-frontend pull request #177
Opened 2020-08-24 11:09 UTC by robert-webb-hmrc

…ical address lookup

# DDCE-1001

##New feature

## PR Suggestions
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???

## Checklist PR Raiser
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

## Checklist PR Reviewer
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2020-08-24 13:17 UTC, abhijeetardale requested changes

2020-08-24 13:17 UTC, abhijeetardale commented on app/connectors/addressLookup/AddressLookupConfiguration.scala
> +    AddressLookupEEAConfigurationModel(
Can we use AddressLookupOptionsModel model with last parameter as
allowedCountryCodes: Option[Set[String]] = None

2020-08-24 13:17 UTC, abhijeetardale commented on app/connectors/addressLookup/AddressLookupConfiguration.scala
> +        allowedCountryCodes =
should be optional set

2020-08-24 13:17 UTC, abhijeetardale commented on app/models/addressLookup/AddressLookupEEAConfigurationModel.scala
> +case class AddressLookupEEAConfigurationModel(version: Int,
not required, please use same model

2020-08-24 13:17 UTC, abhijeetardale commented on app/models/addressLookup/AddressLookupEEAOptionsModel.scala
> +                                        phaseFeedbackLink: SafeRedirectUrl,
not required please use same model

2020-08-24 13:17 UTC, abhijeetardale commented on app/connectors/addressLookup/AddressLookupConnector.scala
> +      AddressLookupEEAConfigurationModel.writes, AddressLookupInitializationReads, hc, ec
please use same model writes

2020-08-24 15:02 UTC, robert-webb-hmrc commented
Updated

2020-08-24 15:52 UTC, abhijeetardale requested changes
could you please check below for Czech Republic, its showing not found however Czechia is present in list which is another name for Czech Republic
![image](https://user-images.githubusercontent.com/26648207/91066736-fa8fd800-e629-11ea-991e-4f33a1d5161d.png)

2020-08-24 16:38 UTC, robert-webb-hmrc commented
Based on the country code Json this is not something we can change as the CZ country code will return Czechia as the country name. This will need further discussion as Czechia is the official name that country is known to the European union as of 2016 http://publications.europa.eu/code/en/en-370100.htm

2020-08-25 08:06 UTC, abhijeetardale approved these changes

2020-08-25 08:06 UTC, merged