DDCE-976: changes related to data Conversion for 'Charity' Object
hmrc/charities-registration-frontend pull request #178
Opened 2020-08-25 09:31 UTC by abhijeetardale

# DDCE-976

##Bug fix / New feature (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## PR Suggestions
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???

## Checklist PR Raiser
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

## Checklist PR Reviewer
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  I've squashed my commits - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2020-08-25 15:28 UTC, robert-webb-hmrc requested changes
Could we get this rebased please, Also these changes require an acceptance test update to the IDs on the "Where does your charity operate?" page.

2020-08-26 13:37 UTC, anburoach commented on app/models/submission/CharityTransformer.scala
> +      ((__ \ 'charityOrganisation \ 'notRegReasonOtherDescription).json.copyFrom((__ \ 'whyNotRegisteredWithCharity).json.pick) orElse doNothing)
Replace 'notRegReasonOtherDescription with 'otherReason

2020-08-26 13:43 UTC, anburoach commented on test/models/submission/CharityTransformerSpec.scala
> +            |			"notRegReasonOtherDescription": "notRegisteredReason"
replace 'notRegReasonOtherDescription with 'otherReason

2020-08-26 13:51 UTC, anburoach requested changes
Changes requested

2020-08-26 14:19 UTC, anburoach approved these changes

2020-08-26 14:29 UTC, merged